Webpage of Portfolio
2004-okari/MY-PORTFOLIO pull request #1
Opened 2023-06-01 19:37 UTC by 2004-okari

It is my 'Portfolio' project and I have made the file in accordance with the requirements.

1. Made a branch named 'webpage'.
2. Linters configuration and run the test.
3. HTML & CSS to create the web page.
4. Made README.md file & MIT.md files

2023-06-01 20:15 UTC, zieeco requested changes
Hi @2004-okari,

<img height="220" src="https://media4.giphy.com/media/bGCwmLDnwL25kCg3FV/giphy-downsized-medium.gif"/>


Great job so far! 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️
- Good code organization

## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 20:15 UTC, zieeco commented on index.html
> +            <div><img src="images/icon-menu.png" alt="icon-menu" id="img-1"></div>
- Hey, to enforce good use of the semantic tag, this should be a nav tag as it would contain the list of the nav items in your webpage. let's improve on this by using the nav tag to improve the page layout.

2023-06-01 20:15 UTC, zieeco commented on index.html
> +                    </p>
- Hey, this content is your main header and should be wrapped with the `h1` tag to improve the semantic usage on your webpage. let's kindly update this.

2023-06-01 20:15 UTC, zieeco commented on index.html
> +                    </div>
- Hey, in here, let's improve our semantic tag usage as these are list items and should be wrapped in the `ul` tag with an `li` holding each `a` tag which wraps each `img`. let's kindly improve on this below:

```html
<ul>
    <li><a href=""><img src="" alt=""></a></li>
</ul>
```

2023-06-01 20:15 UTC, zieeco commented on index.html
> +        <header class="header">
- Hey, the header is a standalone section in a webpage and should not be wrapped in a `section` container as you've used. let's kindly remove the added section here that wraps the header tag to improve our page layout and semantic usage.

2023-06-01 20:15 UTC, zieeco commented on index.html
> +            <section class="section-1">
- Hey, let's also add the missing background image of this section to improve our design as seen in the Figma design below:


*your design*
![image](https://github.com/2004-okari/MY-PORTFOLIO/assets/59397159/5e179f4a-1eb0-4ee6-b9e8-f7976bf8e9de)

*Figma design*
![image](https://github.com/2004-okari/MY-PORTFOLIO/assets/59397159/831874cc-d68a-4685-b9d6-8b65f33f1f40)

2023-06-01 20:15 UTC, zieeco commented on index.html
> +            <div id="logo-text">My Logo</div>
- Hey, your logo should be wrapped in an `a` tag to make it clickable as is meant to be a link that would take users to the home page which is the `index.html`. please, let's update this to improve our layout.

2023-06-01 20:15 UTC, zieeco commented on README.md
> +gem install
- Hey, this is a html-css project, you should use the `npm install` command which will install all the dependencies used and it's not a ruby or rails project. please, update this command.

2023-06-01 20:15 UTC, zieeco commented on README.md
> +
- Hey, this is your portfolio project, and from the project milestone, you won't be adding a login feature. kindly check the project requirement to see a bigger picture of what your feature features will be. see the image below to update this section of your readme:

![image](https://github.com/2004-okari/MY-PORTFOLIO/assets/59397159/130675e3-e20a-4da5-ad27-4717e3f5016c)

2023-06-01 20:15 UTC, zieeco commented on README.md
> +
- Hey, let's make this more descriptive by adding the key feature you've worked on. e.g.: The portfolio mobile version section. you can choose to add more. please, update this to make your readme more professional.

2023-06-02 07:35 UTC, Kamba56 reviewed
Hi @2004-okari 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Linters chacks is not running on your PR, kindly fix that please 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-02 08:15 UTC, 2004-okari commented
Hello. Can you guide me through it via a zoom call?

> On Jun 2, 2023, at 10:35 AM, Toma John Musa ***@***.***> wrote:
> 
> 
> @Kamba56 commented on this pull request.
> 
> Hi @2004-okari <https://github.com/2004-okari>
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> Invalid Code Review Request
> 
> Linters chacks is not running on your PR, kindly fix that please
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> Please, remember to tag me in your question so I can receive the notification.
> 
> Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
> 
> Invalid Code Review Request does not count into the code reviews limit.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/2004-okari/MY-PORTFOLIO/pull/1#pullrequestreview-1456815001>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/A3YS3NGZ6ENYYHDIN46Z7HDXJGJVJANCNFSM6AAAAAAYXMEZDM>.
> You are receiving this because you were mentioned.
>

2023-06-02 09:51 UTC, TuyishimireEric commented
# INVALID ❌ ❌ ❌
### Hi @2004-okari 👋

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Code Review Request ❌
You have submitted a project that is not checking for Linter Errors 😨, Kindly configure Linters and submit again once you are done 🙏  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Kindly create  a new PR that follows the Gitflow approach

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

---
_Invalid Code Review Request does not count into the code reviews limit._

2023-06-02 09:56 UTC, 2004-okari commented
Can you guide me via a zoom call since i have tried configuring linters twice
  

  

  

  
  
  
  
  
>   
> On 2 Jun 2023 at 12:52 pm, Tuyishimire Eric  ***@***.***>  wrote:
>   
>   
> INVALID ❌ ❌ ❌
>   
> Hi  @2004-okari  👋
>   
>
> While you made a great effort in this project, I can't go ahead and review your code.
>
>   
> Invalid Code Review Request ❌
>   
>
> You have submitted a project that is not checking for Linter Errors 😨, Kindly configure Linters and submit again once you are done 🙏
>
>   
>
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
>
>   
>
> Kindly create a new PR that follows the Gitflow approach
>
>   
>
> Cheers and Happy coding!👏👏👏
>
>   
>
> ✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
>  Remember to tag me in your question so I can receive the notification.
>
>   
>
> ⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
>
>     
>
> Invalid Code Review Request does not count into the code reviews limit.
>
>   
>
> —
>  Reply to this email directly,   view it on GitHub, or   unsubscribe.
>  You are receiving this because you were mentioned.Message ID:  ***@***.***>
>
>

2023-06-02 13:06 UTC, BregornOriginal requested changes
Hi @2004-okari  

Good job so far!

There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

![giphy (5)](https://github.com/2004-okari/MY-PORTFOLIO/assets/93630700/fcc6d4cc-1152-4470-9d0d-8c3e9bf9b141)

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-06-02 13:06 UTC, BregornOriginal commented on index.html
> +                    I'm a software developer
- [ ] Good work adding the `h1` tag as was requested by the previous reviewer, kindly use only one `h1` tag for each page as it follows best practices of HTML. In this case would be great to leave only your `h1` with class `article`

2023-06-02 13:06 UTC, BregornOriginal commented on index.html
> +        <section class="section-1">
- [ ] Good work adding your background image inside your `section`. Kindly fix the position of it to match the Figma design

![image](https://github.com/2004-okari/MY-PORTFOLIO/assets/93630700/2d9b884e-aade-4dfd-8c58-84e0d2c39452)

2023-06-02 15:00 UTC, ichala approved these changes
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes Implemented ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-12 13:22 UTC, closed without merging